### ISSUE TITLE
When I use the model I trained, I get an error. Is this related to the number of channels?

### ISSUE THREAD

**Issue by ho-adam** [ZJCV/RotNet#6]
size mismatch for backbone.first_stem.0.weight: copying a param with shape torch.Size([16, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3]).

**Comment by zjykzj** [comment]
> size mismatch for backbone.first_stem.0.weight: copying a param with shape torch.Size([16, 1, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3]).

Give me more info. Did you mean `weights/model.pth`? How many input channels have you set for the training model?

**Comment by ho-adam** [comment]
I trained according to the dataset and pre-model you provided. After the model is generated, using demo.py get an error.

**Comment by zjykzj** [comment]
> 

wowo, the file in `configs/mbv3_small_se_hsigmoid_fmnist_224_e100.yaml` has 3 channels inputs setting

```
  BACKBONE:
    NAME: 'MobileNetV3'
    ARCH: 'mobilenetv3-small'
    IN_PLANES: 3  
``` 

the file `demo/mbv3_small_se_hsigmoid_fmnist_224_e100.yaml .yaml` has 1 channels inputs setting

```
  BACKBONE:
    NAME: 'MobileNetV3'
    ARCH: 'mobilenetv3-small'
    IN_PLANES: 1
```

and the pretrained weight `weights/model.pth` has 1 channels inputs setting

**Comment by zjykzj** [comment]
> I trained according to the dataset and pre-model you provided. After the model is generated, using demo.py get an error.

wowo, the file in `configs/mbv3_small_se_hsigmoid_fmnist_224_e100.yaml` has 3 channels inputs setting

```
  BACKBONE:
    NAME: 'MobileNetV3'
    ARCH: 'mobilenetv3-small'
    IN_PLANES: 3  
```

the file `demo/mbv3_small_se_hsigmoid_fmnist_224_e100.yaml ` has 1 channels inputs setting

```
  BACKBONE:
    NAME: 'MobileNetV3'
    ARCH: 'mobilenetv3-small'
    IN_PLANES: 1
```

and the pretrained weight `weights/model.pth` has 1 channels inputs setting
